# Generated by Django 5.1.4 on 2025-02-06 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexao_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_id', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=255)),
                ('value_id', models.CharField(blank=True, max_length=20, null=True)),
                ('value_name', models.CharField(max_length=255)),
                ('values', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_id', models.IntegerField(null=True)),
                ('value_name', models.CharField(max_length=50)),
                ('values', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category_id', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_quantity', models.PositiveIntegerField()),
                ('condition', models.CharField(max_length=20)),
                ('pictures', models.ImageField(upload_to='media/product_pictures/')),
                ('description', models.TextField()),
                ('attributes', models.ManyToManyField(to='conexao_api.atributos')),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type_id', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=20)),
                ('pictures', models.JSONField()),
                ('description', models.TextField()),
                ('shipping', models.JSONField()),
                ('sale_term', models.CharField(max_length=20)),
                ('warranty', models.CharField(max_length=255)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conexao_api.product')),
                ('sale_terms', models.ManyToManyField(to='conexao_api.saleterm')),
            ],
        ),
    ]
